# Generated by Django 4.2.2 on 2023-06-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_baseprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images/default.png', upload_to='media\\images')),
            ],
        ),
        migrations.AlterField(
            model_name='baseprofilemodel',
            name='profile_pic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.profilepicmodel'),
        ),
    ]
