# Generated by Django 4.2.2 on 2023-06-19 09:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0005_rename_worktitles_jobtitles'),
        ('user_app', '0007_baseprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofilemodel',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='commons_app.citymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+16044011234", max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='zip_code',
            field=models.CharField(default=90001, max_length=9),
            preserve_default=False,
        ),
    ]
