# Generated by Django 4.2.2 on 2023-06-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_baseprofilemodel_banner_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
