# Generated by Django 4.2.2 on 2023-06-29 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_ratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='stars',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
