# Generated by Django 4.2.2 on 2023-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_baseprofilemodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofilemodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='baseprofilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
