# Generated by Django 4.2.2 on 2023-06-20 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_baseprofilemodel_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofilemodel',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='ProfilePicturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
