# Generated by Django 4.2.2 on 2023-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_remove_baseprofilemodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicturesmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
