# Generated by Django 4.2.2 on 2023-06-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0007_alter_trainings_options'),
        ('user_app', '0015_alter_profilepicturesmodel_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_to_work', models.BooleanField(default=True)),
                ('completed_trainings', models.ManyToManyField(blank=True, to='commons_app.trainings')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='commons_app.jobtitles')),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree_type', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
