# Generated by Django 4.2.2 on 2023-06-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_providerprofilemodel_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofilemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
