# Generated by Django 4.2.2 on 2023-06-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0007_alter_trainings_options'),
        ('user_app', '0017_providerprofilemodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofilemodel',
            options={'verbose_name': 'provider profile', 'verbose_name_plural': 'provider profiles'},
        ),
        migrations.AlterField(
            model_name='providerprofilemodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons_app.jobtitles'),
        ),
    ]
