# Generated by Django 4.2.2 on 2023-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_alter_providerprofilemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofilemodel',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='baseprofilemodel',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
