# Generated by Django 4.2.2 on 2023-06-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_alter_providerprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmodel',
            name='description',
        ),
    ]
