# Generated by Django 4.2.2 on 2023-06-22 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0007_alter_trainings_options'),
        ('user_app', '0023_remove_educationmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodel',
            options={'verbose_name': 'education record', 'verbose_name_plural': 'education records'},
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons_app.citymodel')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commons_app.jobtitles')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
