# Generated by Django 4.2.2 on 2023-06-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0007_alter_trainings_options'),
        ('user_app', '0024_alter_educationmodel_options_experiencemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons_app.jobtitles'),
        ),
    ]
