# Generated by Django 4.2.2 on 2023-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_alter_experiencemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
