# Generated by Django 4.2.2 on 2023-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_alter_experiencemodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='work_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Part time'), (1, 'Full time')], default=1),
            preserve_default=False,
        ),
    ]
