# Generated by Django 4.2.2 on 2023-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_alter_experiencemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicturesmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures', verbose_name='profile picture'),
        ),
    ]
