# Generated by Django 4.2.2 on 2023-07-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'get_latest_by': 'timestamp', 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='posted_at',
            new_name='timestamp',
        ),
    ]
