# Generated by Django 4.2.2 on 2023-07-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notificationmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='generated_by',
        ),
    ]
