# Generated by Django 4.2.2 on 2023-06-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facility_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='images/default.png', upload_to='Backend/media/images')),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.PositiveIntegerField(validators=[facility_app.models.validate_zipcode])),
                ('phone_number', models.PositiveIntegerField(validators=[facility_app.models.validate_ten_digits], verbose_name='phone number')),
                ('documents_applicant', models.FileField(upload_to='Backend/media', validators=[facility_app.models.validate_file_size])),
                ('professional_information', models.TextField()),
                ('achievement_information', models.TextField()),
                ('bank_account', models.PositiveBigIntegerField()),
                ('instagram_info', models.URLField(max_length=500)),
                ('facebook_info', models.URLField(max_length=500)),
                ('bank_update_count', models.PositiveIntegerField(blank=True, default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_app.citymodel')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Facility Profile',
                'verbose_name_plural': 'Manage Facilities Profiles',
            },
        ),
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField()),
                ('credentials', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('purpose_of_job', models.CharField(max_length=255)),
                ('status_of_job', models.CharField(choices=[('Open', 'Open'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Open', max_length=255)),
                ('job_filter', models.CharField(choices=[('MD', 'MD'), ('MBBS', 'MBBS'), ('DCH', 'DCH'), ('General', 'General'), ('Cardiologist', 'Cardiologist')], max_length=255, verbose_name='job open for')),
                ('address', models.CharField(max_length=255)),
                ('facility_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility_app.facilitymodel')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Job Post',
                'verbose_name_plural': 'Manage Job Posting',
            },
        ),
        migrations.CreateModel(
            name='FacilityWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Balance')),
                ('add_to_wallet', models.PositiveBigIntegerField(blank=True, null=True)),
                ('withdrawal_from_wallet', models.PositiveBigIntegerField(blank=True, null=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_id', to='facility_app.facilitymodel', verbose_name='Facility Email')),
            ],
            options={
                'verbose_name': 'Manage Wallet',
                'verbose_name_plural': 'Manage Wallets',
            },
        ),
    ]
