# Generated by Django 4.2.2 on 2023-06-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facility_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255, unique=True)),
                ('documents_applicant', models.FileField(upload_to='Backend/media', validators=[facility_app.models.validate_file_size])),
                ('professional_information', models.TextField()),
                ('achivements_info', models.TextField(default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Facility Profile',
                'verbose_name_plural': 'Manage Facilities Profiles',
            },
        ),
    ]
