# Generated by Django 4.2.2 on 2023-06-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0001_initial'),
        ('facility_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Vote')),
                ('average_rating', models.PositiveBigIntegerField(blank=True, null=True)),
                ('facility_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility_app.facilitymodel')),
            ],
            options={
                'verbose_name': 'Manage Facility Rating Avg',
                'verbose_name_plural': 'Manage Facilites Ratings Avg',
            },
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='facility_app.facilitymodel')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='provider_app.providermodel')),
            ],
            options={
                'verbose_name': 'Manage Facility Rating',
                'verbose_name_plural': 'Manage Facilites Ratings',
            },
        ),
        migrations.CreateModel(
            name='HiringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_open_for', models.CharField(choices=[('Allergy and Asthma', 'Allergy and Asthma'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('General surgery', 'General surgery'), ('MD', 'MD'), ('Medical Director Only', 'Medical Director Only'), ('BHT/ Medical Staff', 'BHT/ Medical Staff')], max_length=255)),
                ('hourly_rate', models.PositiveIntegerField()),
                ('interview_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('facility_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility_app.facilitymodel', verbose_name='Facility')),
                ('provider_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel')),
            ],
            options={
                'verbose_name': 'Manage Hiring Request',
                'verbose_name_plural': 'Manage Hiring Requests',
            },
        ),
    ]
