# Generated by Django 4.2.2 on 2023-06-16 06:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility_app', '0002_totalratingmodel_ratingmodel_hiringmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostmodel',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='status_of_job',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='from_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 6, 33, 29, 387805, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='job_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Cancelled'), (2, 'Finished')], default=0, verbose_name='status of the job'),
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='to_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 6, 33, 33, 964440, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='hourly_rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
