# Generated by Django 4.2.2 on 2023-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0003_rename_address_jobpostmodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='purpose_of_job',
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='job_description',
            field=models.CharField(default='Test Description', help_text='Description for the job', max_length=255),
            preserve_default=False,
        ),
    ]
