# Generated by Django 4.2.2 on 2023-06-16 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0001_initial'),
        ('provider_app', '0023_alter_providermodel_city'),
        ('facility_app', '0004_remove_jobpostmodel_purpose_of_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='commons_app.citymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='zip_code',
            field=models.CharField(default='7865023', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons_app.citymodel'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='hourly_rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='CityModel',
        ),
    ]
