# Generated by Django 4.2.2 on 2023-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0005_jobpostmodel_city_jobpostmodel_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='job_title',
            field=models.CharField(default='ABCD', max_length=255),
            preserve_default=False,
        ),
    ]
