# Generated by Django 4.2.2 on 2023-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0006_jobpostmodel_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostmodel',
            old_name='job_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='job_filter',
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='open_for',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('MBBS', 'MBBS'), ('DCH', 'DCH'), ('General', 'General'), ('Cardiologist', 'Cardiologist')], max_length=255, null=True, verbose_name='job open for'),
        ),
    ]
