# Generated by Django 4.2.2 on 2023-06-16 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0009_remove_jobpostmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
