# Generated by Django 4.2.2 on 2023-06-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0010_jobpostmodel_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='open_for',
        ),
    ]
