# Generated by Django 4.2.2 on 2023-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0012_jobpostmodel_city_jobpostmodel_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
