# Generated by Django 4.2.2 on 2023-06-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0027_delete_jobapplications'),
        ('facility_app', '0013_alter_jobpostmodel_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostModel',
        ),
    ]
