# Generated by Django 4.2.2 on 2023-06-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0004_worktitles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkTitles',
            new_name='JobTitles',
        ),
    ]
