# Generated by Django 4.2.2 on 2023-06-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons_app', '0006_trainings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainings',
            options={'verbose_name': 'training', 'verbose_name_plural': 'trainings'},
        ),
    ]
