# Generated by Django 4.2.2 on 2023-06-12 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_alter_customuser_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_pic', models.ImageField(default='images/default.png', upload_to='Backend/media/images/default.png')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='phone number')),
                ('city', models.CharField(blank=True, choices=[('New York', 'New York'), ('San Francisco', 'San Franciso'), ('Boston', 'Boston'), ('Houston', 'Houston'), ('Texas', 'Texas')], max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('available', models.CharField(blank=True, choices=[('available', 'available'), ('not available', 'not available')], max_length=255, null=True)),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('resume', models.FileField(max_length=255, upload_to='')),
                ('job_description', models.CharField(max_length=255)),
                ('employment_verfication', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('orignal_degree', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('license_and_verfication', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('dea_license', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('cds_license', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('npdb', models.FileField(blank=True, help_text='MD Only', max_length=255, null=True, upload_to='')),
                ('peer_attestation_form', models.FileField(blank=True, help_text='Medical Director Only', max_length=255, null=True, upload_to='')),
                ('cpr_certification', models.FileField(blank=True, help_text='BHT/ Medical staff', max_length=255, null=True, upload_to='')),
                ('bank_account', models.PositiveBigIntegerField(blank=True, null=True)),
                ('instagram_info', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_info', models.URLField(blank=True, max_length=500, null=True)),
                ('I_9_Form', models.FileField(max_length=255, upload_to='')),
                ('id_proof', models.FileField(max_length=255, upload_to='')),
                ('w4_w9_1099', models.FileField(help_text='w4/ w9/ 1099', max_length=255, upload_to='')),
                ('check_registry', models.FileField(max_length=255, upload_to='')),
                ('state_background_check', models.FileField(max_length=255, upload_to='')),
                ('orientation', models.BooleanField(default=False)),
                ('confidentiality', models.BooleanField(default=False)),
                ('infection_prevention_and_control', models.BooleanField(default=False, help_text='Infection Prevention and Control')),
                ('pain_management', models.BooleanField(default=False)),
                ('universal_precautions', models.BooleanField(default=False)),
                ('patient_rights', models.BooleanField(default=False)),
                ('child_elder_or_disabled_abuse', models.BooleanField(default=False, help_text='Child/ Elder/ or Disabled Abuse')),
                ('emergency_plan_or_procedures', models.BooleanField(default=False, help_text='Emergency Plan and Procedures')),
                ('co_occurring_disorders', models.BooleanField(default=False, help_text='Co-Occurring Disorders')),
                ('conflict_of_interest', models.BooleanField(default=False)),
                ('cultural_diversity', models.BooleanField(default=False)),
                ('ethics', models.BooleanField(default=False)),
                ('domestic_violence', models.BooleanField(default=False)),
                ('sexual_assault_and_abuse', models.BooleanField(default=False, help_text='Sexual Assault and Abuse')),
                ('tuberculosis', models.BooleanField(default=False)),
                ('fire_safety_fire_extinguisher_training', models.BooleanField(default=False, help_text='Fire Safety/ Fire Extinguisher Training')),
                ('pre_hiring_health_assessment', models.FileField(help_text='Pre-Hire Health Assessment', max_length=255, upload_to='')),
                ('tb_screening', models.FileField(max_length=255, upload_to='')),
                ('immunization_record', models.FileField(max_length=255, upload_to='')),
                ('flu_vaccination', models.FileField(max_length=255, upload_to='')),
                ('drug_screen', models.FileField(max_length=255, upload_to='')),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('bank_update_count', models.PositiveIntegerField(blank=True, default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.servicemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Provider Profile',
                'verbose_name_plural': 'Manage Providers Profiles',
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Balance')),
                ('withdrawal_from_wallet', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProviderEmail', to='provider_app.providermodel', verbose_name='Provider Email')),
            ],
            options={
                'verbose_name': 'Manage Wallet',
                'verbose_name_plural': 'Manage Wallets',
            },
        ),
        migrations.CreateModel(
            name='ApplyJobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.FileField(upload_to='provider_app\\media\\provider_app_images')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_app.jobpostmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel', verbose_name='Provider Email')),
            ],
            options={
                'verbose_name': 'Manage Applied Job Post',
                'verbose_name_plural': 'Manage Applied Jobs Posts',
            },
        ),
    ]
