# Generated by Django 4.2.2 on 2023-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationsmodel',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
