# Generated by Django 4.2.2 on 2023-06-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0002_totalratingmodel_ratingmodel_hiringmodel'),
        ('provider_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTotalRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Vote')),
                ('average_rating', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel')),
            ],
            options={
                'verbose_name': 'Manage Pro Rating Avg',
                'verbose_name_plural': 'Manage Pro Ratings Avg',
            },
        ),
        migrations.CreateModel(
            name='ProviderRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_app.facilitymodel')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel')),
            ],
            options={
                'verbose_name': 'Manage Provider Rating',
                'verbose_name_plural': 'Manage Provider Ratings',
            },
        ),
    ]
