# Generated by Django 4.2.2 on 2023-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0002_providertotalratingmodel_providerratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
