# Generated by Django 4.2.2 on 2023-06-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0002_totalratingmodel_ratingmodel_hiringmodel'),
        ('provider_app', '0003_alter_providermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_app.citymodel'),
        ),
    ]
