# Generated by Django 4.2.2 on 2023-06-12 05:10

from django.db import migrations, models
import provider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0006_alter_providermodel_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='zipcode',
            field=models.PositiveIntegerField(validators=[provider_app.models.validate_zipcode]),
        ),
    ]
