# Generated by Django 4.2.2 on 2023-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0007_alter_providermodel_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='available',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
