# Generated by Django 4.2.2 on 2023-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0008_alter_providermodel_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='bank_account',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
