# Generated by Django 4.2.2 on 2023-06-12 07:03

from django.db import migrations, models
import provider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0009_alter_providermodel_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobpostmodel',
            name='cover_letter',
            field=models.FileField(upload_to='media/provider_app', validators=[provider_app.models.validate_file_size]),
        ),
    ]
