# Generated by Django 4.2.2 on 2023-06-12 07:11

from django.db import migrations, models
import provider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0011_alter_applyjobpostmodel_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobpostmodel',
            name='cover_letter',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='I_9_Form',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='cds_license',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='check_registry',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='cpr_certification',
            field=models.FileField(help_text='BHT/ Medical staff', upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='dea_license',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='drug_screen',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='employment_verfication',
            field=models.FileField(upload_to='', validators=[provider_app.models.validate_file_size], verbose_name='Backend/media/provider_app_documents'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='flu_vaccination',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='id_proof',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='immunization_record',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='license_and_verfication',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='npdb',
            field=models.FileField(help_text='MD Only', upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='orignal_degree',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='peer_attestation_form',
            field=models.FileField(help_text='Medical Director Only', upload_to='', validators=[provider_app.models.validate_file_size], verbose_name='Backend/media/provider_app_documents'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='pre_hiring_health_assessment',
            field=models.FileField(help_text='Pre-Hire Health Assessment', upload_to='', validators=[provider_app.models.validate_file_size], verbose_name='Backend/media/provider_app_documents'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='resume',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='state_background_check',
            field=models.FileField(upload_to='', validators=[provider_app.models.validate_file_size], verbose_name='Backend/media/provider_app_documents'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='tb_screening',
            field=models.FileField(upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='w4_w9_1099',
            field=models.FileField(help_text='w4/ w9/ 1099', upload_to='media/provider_app_documents', validators=[provider_app.models.validate_file_size]),
        ),
    ]
