# Generated by Django 4.2.2 on 2023-06-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0013_alter_providermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='Backend/media/images/default.png'),
        ),
    ]
