# Generated by Django 4.2.2 on 2023-06-12 08:39

from django.db import migrations, models
import provider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0015_alter_applyjobpostmodel_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='employment_verfication',
            field=models.FileField(upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='peer_attestation_form',
            field=models.FileField(help_text='Medical Director Only', upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='pre_hiring_health_assessment',
            field=models.FileField(help_text='Pre-Hire Health Assessment', upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='state_background_check',
            field=models.FileField(upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
    ]
