# Generated by Django 4.2.2 on 2023-06-12 08:42

from django.db import migrations, models
import provider_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0016_alter_providermodel_employment_verfication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='cpr_certification',
            field=models.FileField(blank=True, help_text='BHT/ Medical staff', null=True, upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='npdb',
            field=models.FileField(blank=True, help_text='MD Only', null=True, upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='peer_attestation_form',
            field=models.FileField(blank=True, help_text='Medical Director Only', null=True, upload_to='', validators=[provider_app.models.validate_file_size]),
        ),
    ]
