# Generated by Django 4.2.2 on 2023-06-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0017_alter_providermodel_cpr_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobpostmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel', verbose_name='Provider Email'),
        ),
    ]
