# Generated by Django 4.2.2 on 2023-06-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0020_remove_providertotalratingmodel_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderTotalRatingModel',
            new_name='ProviderAverageRatingModel',
        ),
    ]
