# Generated by Django 4.2.2 on 2023-06-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0021_rename_providertotalratingmodel_provideraverageratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideraverageratingmodel',
            name='average_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provideraverageratingmodel',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
