# Generated by Django 4.2.2 on 2023-06-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility_app', '0013_alter_jobpostmodel_zip_code'),
        ('provider_app', '0023_alter_providermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_app.jobpostmodel')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider_app.providermodel', verbose_name='Provider Email')),
            ],
            options={
                'verbose_name': 'Manage Applied Job Post',
                'verbose_name_plural': 'Manage Applied Jobs Posts',
            },
        ),
        migrations.DeleteModel(
            name='ApplyJobPostModel',
        ),
    ]
