# Generated by Django 4.2.2 on 2023-06-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider_app', '0024_jobapplications_delete_applyjobpostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='user_id',
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='user',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
            preserve_default=False,
        ),
    ]
