# Generated by Django 4.2.2 on 2023-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0025_remove_jobapplications_user_id_jobapplications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
