# Generated by Django 4.2.2 on 2023-06-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0026_alter_jobapplications_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplications',
        ),
    ]
