# Generated by Django 4.2.2 on 2023-06-28 07:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons_app', '0007_alter_trainings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('credentials', models.TextField()),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('job_timings', models.PositiveSmallIntegerField(choices=[(0, 'Part time'), (1, 'Full time')])),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.CharField(help_text='Description for the job', max_length=255)),
                ('job_status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Cancelled'), (2, 'Finished')], default=0, verbose_name='status of the job')),
                ('location', models.CharField(max_length=255)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons_app.citymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Job Post',
                'verbose_name_plural': 'Manage Job Posting',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_app.jobpostmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Manage Applied Job Post',
                'verbose_name_plural': 'Manage Applied Jobs Posts',
            },
        ),
    ]
