# Generated by Django 4.2.2 on 2023-06-29 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_alter_jobapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Waiting for response'), (1, 'Applied'), (2, 'Accepted'), (3, 'Rejected')], default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
