# Generated by Django 4.2.2 on 2023-06-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_jobtitles_trainings_userlanguages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainings',
            new_name='JobTitlesModel',
        ),
        migrations.RenameModel(
            old_name='UserLanguages',
            new_name='TrainingsModel',
        ),
        migrations.RenameModel(
            old_name='JobTitles',
            new_name='UserLanguagesModel',
        ),
        migrations.AlterModelOptions(
            name='jobtitlesmodel',
            options={'verbose_name': 'work title', 'verbose_name_plural': 'work titles'},
        ),
        migrations.AlterModelOptions(
            name='trainingsmodel',
            options={'verbose_name': 'Provider training', 'verbose_name_plural': 'Providers trainings'},
        ),
        migrations.AlterModelOptions(
            name='userlanguagesmodel',
            options={'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.RenameField(
            model_name='jobtitlesmodel',
            old_name='training_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='trainingsmodel',
            old_name='language',
            new_name='training_name',
        ),
        migrations.RenameField(
            model_name='userlanguagesmodel',
            old_name='title',
            new_name='language',
        ),
    ]
