# Generated by Django 4.2.2 on 2023-06-20 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_profilepicmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
