# Generated by Django 4.2.2 on 2023-06-28 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider_app', '0004_rename_profilepicturesmodel_profilepicturesserializer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicturesSerializer',
            new_name='ProfilePicturesModel',
        ),
    ]
